export enum HomeImages {
  vanPic = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/me+in+a+van.jpeg',
}

export enum AboutImages {
  meAtYosemite = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/me+at+yosemite.jpg',
}

export enum TravelPreviewImages {
  fourStateRoadTrip2022 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/2022-usa-roadtrip.jpg',
  sanFran2022 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/san-fran-2021.jpg',
  austin2021 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/austin.jpg',
  westTexas2021 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/west+texas.jpg',
  miami2021 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/miami.jpg',
  toronto2020 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/toronto.jpg',
  france2019 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/france.jpg',
  vietnam2019 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel-previews/vietnam.jpg',
}

export enum France2019Images {
  annecy = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy.jpg',
  annecy2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy2.jpg',
  annecy3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy3.jpg',
  annecy4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy4.jpg',
  annecy5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy5.jpg',
  annecy6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy6.jpg',
  annecy7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy17better.jpeg',
  annecy8 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy8.jpg',
  annecy9 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy9.jpg',
  annecy10 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy10.jpg',
  annecy11 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy11.jpeg',
  annecy12 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy12.jpeg',
  annecy13 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy13.jpeg',
  annecy14 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy14.jpeg',
  annecy15 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy15.jpeg',
  annecy16 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy16.jpeg',
  annecy18 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy18.jpeg',
  annecy19 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy19.jpeg',
  annecy20 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy20.jpeg',
  annecy21 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy21.jpg',
  annecy22 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/annecy22.jpg',
  paris1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris1.jpg',
  paris2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris2.jpg',
  paris3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris3.jpg',
  paris4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris4.jpg',
  paris5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris5.jpg',
  paris6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris6.jpg',
  paris7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris7.jpg',
  paris8 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris8.jpg',
  paris9 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris9.jpg',
  paris10 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris10.jpg',
  paris11 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris11.jpg',
  paris12 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris12.jpg',
  paris13 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris13.jpg',
  paris14 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris14.jpg',
  paris15 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris15.jpg',
  paris16 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris16.jpeg',
  paris17 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris17.jpeg',
  paris18 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris18.jpeg',
  paris19 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris19.jpeg',
  paris20 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris20.jepg',
  paris21 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris21.jpeg',
  paris22 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris22.jpeg',
  paris23 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris23.jpeg',
  paris24 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris24.jpeg',
  paris25 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris25.jpeg',
  paris26 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris26.jpeg',
  paris27 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris27.jpeg',
  paris28 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris28.jpeg',
  paris29 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris29.jpeg',
  paris30 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris30.jpeg',
  paris31 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris31.jpeg',
  paris32 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris32.jpeg',
  paris33 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris33.jpeg',
  paris34 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris34.jpeg',
  paris35 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris35.jpeg',
  paris36 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris36.jpeg',
  paris37 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris37.jpeg',
  paris38 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris38.jpeg',
  paris39 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris39.jpeg',
  paris41 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris41.jpeg',
  paris42 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris42.jpeg',
  paris43 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris43.jpeg',
  paris44 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris44.jpeg',
  paris45 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris45.jpeg',
  paris46 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris46.jpeg',
  paris47 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris47.jpeg',
  paris48 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris48.jpeg',
  paris49 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris49.jpeg',
  paris50 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris50.jpeg',
  paris51 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/paris51.jpeg',
  nice1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice1.jpg',
  nice2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice2.jpg',
  nice3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice3.jpg',
  nice4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice4.jpg',
  nice5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice5.jpg',
  nice6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice6.jpg',
  nice7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/nice7.jpg',
  monaco1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco1.jpg',
  monaco2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco2.jpg',
  monaco3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco3.jpg',
  monaco4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco4.jpg',
  monaco5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco5.jpg',
  monaco6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/monaco6.jpg',
  saintTropez1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez1.jpg',
  saintTropez2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez2.jpg',
  saintTropez3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez3.jpg',
  saintTropez4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez4.jpg',
  saintTropez5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez5.jpg',
  saintTropez6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez6.jpg',
  saintTropez7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez7.jpg',
  saintTropez8 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez8.jpg',
  saintTropez9 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/tropez9.jpg',
  bordeaux1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux1.jpg',
  bordeaux2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux2.jpg',
  bordeaux3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux3.jpg',
  bordeaux4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux4.jpg',
  bordeaux5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux5.jpg',
  bordeaux6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux6.jpg',
  bordeaux7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux7.jpg',
  bordeaux8 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/bordeaux8.jpg',
  saintEmilion1 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion1.jpg',
  saintEmilion2 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion2.jpg',
  saintEmilion3 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion3.jpg',
  saintEmilion4 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion4.jpg',
  saintEmilion5 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion5.jpg',
  saintEmilion6 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion6.jpg',
  saintEmilion7 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion7.jpg',
  saintEmilion8 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion8.jpg',
  saintEmilion9 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion9.jpg',
  saintEmilion10 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion10.jpg',
  saintEmilion11 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion11.jpg',
  saintEmilion12 = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/france-2019/emillion12.jpg',
}

export enum Vietnam2019Images {
  bunCha = 'https://jakeraw-images.s3.us-east-2.amazonaws.com/travel/vietname-2019/Bu%CC%81n+cha%CC%89.jpeg',
}
